"""migration

Revision ID: c1676573d873
Revises: b2fd43da64df
Create Date: 2024-08-23 14:36:05.605884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1676573d873'
down_revision = 'b2fd43da64df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
